### ISSUE TITLE
Scrolling in left panel is a lie and native scrollbar reveals it!

### ISSUE THREAD

**Issue by jirutka** [grissius/markup-editor#32]
Focus on scrollbars:

![Screencast demonstrating the issue](https://user-images.githubusercontent.com/949228/33341988-6c8efdd0-d478-11e7-9e59-2fd054d154e1.gif)

This is not caused by page zoom, the behvaiour is the same when the page is not zoomed out.

I’m not sure if it’s even possible to implement it to behave correctly with native scrollbars…

**Browser:** Firefox 55.0.3 on macOS

**Comment by grissius** [comment]
They are hidden on chrome, have not tested FF. Will look into it.
Yes they are a lie. A good lie in Chrome.

Hiding scrollbars is hacky, true that; but if cross-browser scrollbar hiding can be achieved flawless-ish, the solution is superb I think.

**Comment by grissius** [comment]
https://blogs.msdn.microsoft.com/kurlak/2013/11/03/hiding-vertical-scrollbars-with-pure-css-in-chrome-ie-6-firefox-opera-and-safari/

This is hell... :fire:

**Comment by jirutka** [comment]
That post is old as dinosaurs in terms of world wide web. It has probably changed since 2013. And you don’t need to give a f*ck about IE 6 anymore. ;)

**Comment by jirutka** [comment]
Have you tried to make it work with native scrollbars? Removing scrollbars (native or faked) is not a good approach IMO.

**Comment by grissius** [comment]
I personally don't give a fuck about FF either :smile: Ehm :neutral_face: 

The only problem with that is the left scrollbar in the GIF. I could get it working without it (the source coude would span over 100% height), but [1] it forces CM to recalculate height on each fart, which introduces lags on large documents and [2] the scrollbar (in source code) would be still absent, since CM does not have it *.

*You ask _wait what, CM does not have scrollbar?_ You can give it all the space it needs (height) and wrap it in div with `overflow:scroll` which is possible, but would require CM to render the whole source in DOM, which might also introduce performance issues on larger docs. CM renders 10 lines ahead by default I believe.

> Have you tried to make it work with native scrollbars? Removing scrollbars (native or faked) is not a good approach IMO.

I have tried that. Either way there was a (major) performance issue or insane fuzz about it (basically handling the scrolling myself, scrolling the CM and simulating the scroll of the container). Or both.

Not super happy about it either.

**Comment by grissius** [comment]
#40 hides them in FF, but scrolling is still buggy in FF with the hacky scrolling.

Rendering the whole CM (CodeMirror, might not be clear from the context -- it's the lib I use for source code editing) contents seems to be the only path to take.

To be honest the scrollsync implementation would be easier as well, now the scrolling is programatically handled on both divs adding the offsets.

### Suggested solution

Whole CM area will always be rendered. Native scrollbars will work as expected without any hacks.

This will result in performance issues on larger documents. A solution to this might be user setting to disable autoscroll on large documents, which will enable CM to render only requested content.

Are you with me @jirutka? What is your opinion on the matter?

**Comment by grissius** [comment]
If I get positive answer for this [topic](https://discuss.codemirror.net/t/get-visible-lines-with-respect-to-current-scroll/1429) I might achieve the result with little to no performance issues.

On **hold** for now.

**Comment by jirutka** [comment]
> I personally don't give a fuck about FF either 😄

You don't give a fuck about truly open and technologically superior (search for Firefox Quantum) browser?! You monster!

> *You ask wait what, CM does not have scrollbar? 

I see, CM do a serious black magic with scrolling. There's a very interesting blog post from CM's developer: http://marijnhaverbeke.nl/blog/a-pathological-scrolling-model.html (the last section is especially interesting).

**Comment by jirutka** [comment]
> Are you with me @jirutka? What is your opinion on the matter?

I don't know. It seems there's no clean solution, only more or less hackish workarounds. :( It will probably require some testing with different browsers and type of contents to find the least broken solution.

I have stronger opinion only in matter of providing the same UI/UX as native scrolling, i.e. including scrollbars (native or faked).

**Comment by grissius** [comment]
Well it turns out, everything changes!

Most embarrassing thing happened: I found out that CM does not have Adoc mode. Don't know how could I miss it, but it happened :neutral_face:

So I am standing at the crossroads, whether it would take less work to implement the highlighter for Adoc in CM myself, or use [Ace](ace.c9.io) instead. Will do a tad bit of research and decide. So far the latter seems to be a better path to take.

But I will need to solve this before drowning more time in CM, since it might be wasted in the end.

**Comment by jirutka** [comment]
I believe it should be possible to port AsciiDoc highlighter from some other editor into CM. I'll look at it too.

**Comment by grissius** [comment]
Thanks!

The only part of implementation dependant on the CM is the synchro scrolling, which will probably have to be rewritten anyway. So jumping into another editor should not be as painful.

The more I read about Ace the more I like it. They brag it should run with as much as 4 mil loc, which is pretty impressive. It also seems to have cleaner api and easier extensibility (subjective impression from a glance) and have greater support for combining/delegating modes from within. (Default MD mode already supports this for snippets for some langs BTW, which is cool) Which I cannot say about CM from the recent experience.

The only thing people dislike about it is the BSD licence, which is said to be more restrictive than CM's MIT, but from my unexpirienced opinion of licences there does not seem to be much difference, except for prohibiting to use the same name. Or is there? I bet you know more about licences. Any advice appriciated!

...and Ace also supports importing modes from sublime :-)

**Comment by grissius** [comment]
Working on Ace integration as a replacement for CM.

I am starting to think this was the best decision in history of decisions maybe ever!
Everything just... works :sparkles: :joy_cat:

**Comment by grissius** [comment]
#45
