### ISSUE TITLE
Cmd+C (copy) in preview panel does not work

### ISSUE THREAD

**Issue by jirutka** [grissius/markup-editor#33]
When I select some text in the preview panel and hit Cmd+C to copy the selection, it does not copy it to the clipboard. However, when I open a context menu (right click) and click on “Copy” here, it does copy the selection to the clipboard. How’s that even possible…? 🙀

**Browser:** Firefox 55.0.3 on macOS

**Comment by grissius** [comment]
Probably bug in contentEditable (#10), think it's not greatly supported.

**Comment by grissius** [comment]
A-ha! I think I know what's going on. As mentioned previously, preview is `contentEditable` (turned out to be a bad choice milion times over). To kill editing features, naive approach of preventing `onChange` event was set. This is probably the cause. In FF `Ctrl+C` is probably not executed, because the event is prevented in the script. Chrome probably does realize that not every keystroke triggers edit and does perfrom clipboard copy.

The resulting behaviour though is peculiar! :sparkles:  :bug: 

Replicated in FF, but in Chrome it works as expected.

**Comment by grissius** [comment]
#47
